app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout
    methods: [GET]

app_main_menu:
    path: /main-menu
    controller: App\Controller\LoginController::mainMenu

app_single_player:
    path: /single-player
    controller: App\Controller\YourController::singlePlayer

app_multiplayer:
    path: /multiplayer
    controller: App\Controller\MultiplayerController::multiplayer

app_match_room:
    path: '/match/{id}/room'
    controller: App\Controller\MatchController::room
    requirements:
        id: '\d+'

app_match_click:
    path: /match/{id}/click
    controller: App\Controller\MatchController::click
    methods: ['POST']
    requirements:
        id: \d+

